namespace MinionMirage.Localization;

public enum UiTextKey
{
    Automatic,
    English,
    Japanese,
    German,
    French,
    Settings,
    UiLanguage,
    Experimental,
    EnableMinionSummonExperiment,
    EnableMinionSummonExperimentHelp,
    Search,
    All,
    Human,
    AdultHuman,
    YoungHuman,
    DemiHuman,
    Monster,
    CardView,
    ListView,
    Target,
    ActiveMappings,
    VisibleMappings,
    NoResults,
    EnableAll,
    DisableAll,
    Enabled,
    Disabled,
    NotOwned,
}
